version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - exhaustive
    - goconst
    - gocritic
    - godot
    - godox
    - goheader
    - gomodguard
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl_v5
